replicaCount: 1

image:
  repository: k3d-java-webserver-sre-registry:5050/java-webserver
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

labels:
  app: "java-webserver"


selectorLabels:
  app: "java-webserver"

fullnameOverride: ""
nameOverride: ""